// Content schema for all /learn articles.
// Each topic defines the metadata and generation inputs.
// Actual article prose lives in content/learn/[slug].json,
// produced by scripts/generateLearnContent.js.

const topics = [
  // ─── Cluster 1: Chart Types ───────────────────────────────────────────────
  {
    slug: "how-to-make-a-bar-chart-from-csv-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "bar chart from CSV data",
    titleTag: "How to Make a Bar Chart from CSV Data | Distill",
    metaDescription:
      "Learn how to make a bar chart from CSV data in Excel and Google Sheets, then try Distill to generate one instantly. Free to use.",
    h1: "How to Make a Bar Chart from CSV Data",
    whatIsLabel: "bar chart",
    relatedSlugs: [
      "how-to-make-a-stacked-bar-chart",
      "how-to-make-a-comparison-chart-in-excel",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-line-chart-to-show-trends",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "line chart to show trends",
    titleTag: "How to Make a Line Chart to Show Trends | Distill",
    metaDescription:
      "Step-by-step guide to making a line chart in Excel and Google Sheets to visualize trends over time. Or let Distill do it from your CSV in seconds.",
    h1: "How to Make a Line Chart to Show Trends",
    whatIsLabel: "line chart",
    relatedSlugs: [
      "how-to-create-a-multi-series-line-chart",
      "how-to-track-monthly-revenue-trends",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-pie-chart-from-a-spreadsheet",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "pie chart from a spreadsheet",
    titleTag: "How to Make a Pie Chart from a Spreadsheet | Distill",
    metaDescription:
      "Learn how to make a pie chart from a spreadsheet in Excel and Google Sheets. Or upload your CSV to Distill and get one instantly. Free to use.",
    h1: "How to Make a Pie Chart from a Spreadsheet",
    whatIsLabel: "pie chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-make-a-comparison-chart-in-excel",
      "how-to-visualize-marketing-funnel-data",
    ],
  },
  {
    slug: "how-to-make-a-scatter-plot-from-csv-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "scatter plot from CSV data",
    titleTag: "How to Make a Scatter Plot from CSV Data | Distill",
    metaDescription:
      "How to make a scatter plot from CSV data in Excel and Google Sheets. Upload to Distill to visualize correlations in your data instantly.",
    h1: "How to Make a Scatter Plot from CSV Data",
    whatIsLabel: "scatter plot",
    relatedSlugs: [
      "how-to-make-a-histogram-from-raw-data",
      "how-to-spot-anomalies-in-your-sales-data",
      "how-to-make-a-bar-chart-from-csv-data",
    ],
  },
  {
    slug: "how-to-make-a-histogram-from-raw-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "histogram from raw data",
    titleTag: "How to Make a Histogram from Raw Data | Distill",
    metaDescription:
      "Learn how to make a histogram from raw data in Excel and Google Sheets. Distill auto-detects numeric columns and builds one for you.",
    h1: "How to Make a Histogram from Raw Data",
    whatIsLabel: "histogram",
    relatedSlugs: [
      "how-to-make-a-scatter-plot-from-csv-data",
      "how-to-spot-anomalies-in-your-sales-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-visualize-a-data-table-without-coding",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "visualize a data table without coding",
    titleTag: "How to Visualize a Data Table Without Coding | Distill",
    metaDescription:
      "Turn a raw data table into meaningful charts with no code required. Step-by-step for Excel and Google Sheets, plus a faster no-setup option.",
    h1: "How to Visualize a Data Table Without Coding",
    whatIsLabel: "data visualization",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-upload-a-spreadsheet-and-get-instant-charts",
    ],
  },
  {
    slug: "how-to-make-a-comparison-chart-in-excel",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "comparison chart in Excel",
    titleTag: "How to Make a Comparison Chart in Excel | Distill",
    metaDescription:
      "How to make a comparison chart in Excel and Google Sheets. Compare categories side by side, or upload your CSV to Distill for instant results.",
    h1: "How to Make a Comparison Chart in Excel",
    whatIsLabel: "comparison chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-make-a-stacked-bar-chart",
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
    ],
  },
  {
    slug: "how-to-make-a-stacked-bar-chart",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "stacked bar chart",
    titleTag: "How to Make a Stacked Bar Chart | Distill",
    metaDescription:
      "Learn how to make a stacked bar chart in Excel and Google Sheets to compare part-to-whole relationships. Or generate one instantly with Distill.",
    h1: "How to Make a Stacked Bar Chart",
    whatIsLabel: "stacked bar chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-make-a-comparison-chart-in-excel",
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
    ],
  },
  {
    slug: "how-to-create-a-multi-series-line-chart",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "multi-series line chart",
    titleTag: "How to Create a Multi-Series Line Chart | Distill",
    metaDescription:
      "How to create a multi-series line chart in Excel and Google Sheets to compare trends across groups. Or upload your CSV to Distill and get it done in seconds.",
    h1: "How to Create a Multi-Series Line Chart",
    whatIsLabel: "multi-series line chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-to-show-trends",
      "how-to-track-monthly-revenue-trends",
      "how-to-create-a-kpi-dashboard-from-csv",
    ],
  },

  // ─── Cluster 2: Business Use Cases ────────────────────────────────────────
  {
    slug: "how-to-build-a-sales-dashboard-from-a-spreadsheet",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "sales dashboard from a spreadsheet",
    titleTag: "Build a Sales Dashboard from a Spreadsheet | Distill",
    metaDescription:
      "Learn how to build a sales dashboard from a spreadsheet in Excel and Google Sheets. See how Distill auto-generates one from your CSV in seconds.",
    h1: "How to Build a Sales Dashboard from a Spreadsheet",
    whatIsLabel: "sales dashboard",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-track-monthly-revenue-trends",
      "how-to-create-a-kpi-dashboard-from-csv",
    ],
  },
  {
    slug: "how-to-track-monthly-revenue-trends",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "track monthly revenue trends",
    titleTag: "How to Track Monthly Revenue Trends | Distill",
    metaDescription:
      "How to track monthly revenue trends using charts in Excel and Google Sheets. Visualize growth, dips, and patterns, or let Distill do it from your CSV.",
    h1: "How to Track Monthly Revenue Trends",
    whatIsLabel: "revenue trend chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-to-show-trends",
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-visualize-marketing-funnel-data",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "visualize marketing funnel data",
    titleTag: "How to Visualize Marketing Funnel Data | Distill",
    metaDescription:
      "Turn your marketing funnel data into clear charts. Step-by-step for Excel and Google Sheets, plus a zero-setup option using Distill.",
    h1: "How to Visualize Marketing Funnel Data",
    whatIsLabel: "marketing funnel chart",
    relatedSlugs: [
      "how-to-make-a-pie-chart-from-a-spreadsheet",
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
    ],
  },
  {
    slug: "how-to-spot-anomalies-in-your-sales-data",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "spot anomalies in sales data",
    titleTag: "How to Spot Anomalies in Your Sales Data | Distill",
    metaDescription:
      "Learn how to spot anomalies in your sales data using charts and formulas in Excel and Google Sheets. Or let Distill flag them automatically from your CSV.",
    h1: "How to Spot Anomalies in Your Sales Data",
    whatIsLabel: "anomaly detection",
    relatedSlugs: [
      "how-to-make-a-histogram-from-raw-data",
      "how-to-make-a-scatter-plot-from-csv-data",
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
    ],
  },
  {
    slug: "how-to-create-a-kpi-dashboard-from-csv",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "KPI dashboard from CSV",
    titleTag: "How to Create a KPI Dashboard from CSV | Distill",
    metaDescription:
      "How to create a KPI dashboard from a CSV file in Excel and Google Sheets. Track key metrics visually, or generate the entire dashboard with Distill.",
    h1: "How to Create a KPI Dashboard from CSV",
    whatIsLabel: "KPI dashboard",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-create-a-multi-series-line-chart",
    ],
  },
  {
    slug: "how-to-turn-a-weekly-report-into-a-visual-dashboard",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "weekly report visual dashboard",
    titleTag: "Turn a Weekly Report into a Visual Dashboard | Distill",
    metaDescription:
      "How to turn a weekly report into a visual dashboard using Excel or Google Sheets. Save hours every week, or upload your CSV to Distill and skip the setup.",
    h1: "How to Turn a Weekly Report into a Visual Dashboard",
    whatIsLabel: "visual dashboard",
    relatedSlugs: [
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
      "how-to-share-a-data-dashboard-with-your-team-for-free",
    ],
  },

  // ─── Cluster 3: CSV to Charts ─────────────────────────────────────────────
  {
    slug: "how-to-turn-a-csv-into-a-chart-instantly",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "turn a CSV into a chart",
    titleTag: "How to Turn a CSV into a Chart Instantly | Distill",
    metaDescription:
      "The fastest ways to turn a CSV into a chart using Excel, Google Sheets, or Distill. No formulas, no setup. Upload and visualize in seconds.",
    h1: "How to Turn a CSV into a Chart Instantly",
    whatIsLabel: "CSV visualization",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-upload-a-spreadsheet-and-get-instant-charts",
      "how-to-convert-excel-data-to-interactive-charts",
    ],
  },
  {
    slug: "how-to-upload-a-spreadsheet-and-get-instant-charts",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "upload spreadsheet get instant charts",
    titleTag: "Upload a Spreadsheet and Get Instant Charts | Distill",
    metaDescription:
      "Learn how to upload a spreadsheet and instantly get charts in Excel, Google Sheets, or with Distill. Every column auto-visualized with no setup required.",
    h1: "How to Upload a Spreadsheet and Get Instant Charts",
    whatIsLabel: "spreadsheet visualization",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
      "how-to-share-a-data-dashboard-with-your-team-for-free",
    ],
  },
  {
    slug: "best-free-tools-to-visualize-csv-data",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "free tools to visualize CSV data",
    titleTag: "Best Free Tools to Visualize CSV Data in 2026 | Distill",
    metaDescription:
      "The best free tools to visualize CSV data in 2026, comparing Excel, Google Sheets, and Distill by speed, features, and ease of use.",
    h1: "Best Free Tools to Visualize CSV Data in 2026",
    whatIsLabel: "CSV visualization tool",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-convert-excel-data-to-interactive-charts",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "convert Excel data to interactive charts",
    titleTag: "Convert Excel Data to Interactive Charts | Distill",
    metaDescription:
      "How to convert Excel data to interactive charts, step by step in Excel and Google Sheets, or instantly with Distill. Free and no-code.",
    h1: "How to Convert Excel Data to Interactive Charts",
    whatIsLabel: "interactive chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-upload-a-spreadsheet-and-get-instant-charts",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-share-a-data-dashboard-with-your-team-for-free",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "share data dashboard with team free",
    titleTag: "Share a Data Dashboard with Your Team for Free | Distill",
    metaDescription:
      "How to share a data dashboard with your team for free using Google Sheets, Notion, or Distill's one-click shareable links. No account needed to view.",
    h1: "How to Share a Data Dashboard with Your Team for Free",
    whatIsLabel: "shareable dashboard",
    relatedSlugs: [
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-turn-a-weekly-report-into-a-visual-dashboard",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },


  {
    slug: "how-to-visualize-time-series-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to visualize time series data",
    titleTag: "How to Visualize Time Series Data | Distill",
    metaDescription: "Visualize time series data from a CSV in Excel, Google Sheets, or Distill. Upload your file and get line charts and trend summaries instantly.",
    h1: "How to Visualize Time Series Data",
    whatIsLabel: "time series chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-to-show-trends",
      "how-to-track-monthly-revenue-trends",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-visualize-survey-results",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "visualize survey results",
    titleTag: "How to Visualize Survey Results | Distill",
    metaDescription: "Turn survey results into clear charts using Excel, Google Sheets, or Distill. Export your CSV and visualize responses in seconds. Free to use.",
    h1: "How to Visualize Survey Results",
    whatIsLabel: "survey results chart",
    relatedSlugs: [
      "how-to-make-a-pie-chart-from-a-spreadsheet",
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-donut-chart",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a donut chart",
    titleTag: "How to Make a Donut Chart | Distill",
    metaDescription: "Learn how to make a donut chart in Excel and Google Sheets, or upload your CSV to Distill and get one instantly. Free, no account required.",
    h1: "How to Make a Donut Chart",
    whatIsLabel: "donut chart",
    relatedSlugs: [
      "how-to-make-a-pie-chart-from-a-spreadsheet",
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-create-an-area-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "area chart from CSV",
    titleTag: "How to Create an Area Chart from CSV | Distill",
    metaDescription: "Create an area chart from a CSV in Excel, Google Sheets, or Distill. Visualize cumulative totals and trends over time in seconds. Free to use.",
    h1: "How to Create an Area Chart from CSV",
    whatIsLabel: "area chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-to-show-trends",
      "how-to-visualize-time-series-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-treemap-chart",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "treemap chart",
    titleTag: "How to Make a Treemap Chart | Distill",
    metaDescription: "Learn how to make a treemap chart in Excel and Google Sheets to show part-to-whole relationships. Or upload your CSV to Distill and get one instantly.",
    h1: "How to Make a Treemap Chart",
    whatIsLabel: "treemap chart",
    relatedSlugs: [
      "how-to-make-a-pie-chart-from-a-spreadsheet",
      "how-to-make-a-stacked-bar-chart",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-bubble-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "bubble chart from CSV",
    titleTag: "How to Make a Bubble Chart from CSV | Distill",
    metaDescription: "Learn how to make a bubble chart from a CSV in Excel and Google Sheets. Or upload your CSV to Distill and get one generated automatically. Free to use.",
    h1: "How to Make a Bubble Chart from CSV Data",
    whatIsLabel: "bubble chart",
    relatedSlugs: [
      "how-to-make-a-scatter-plot-from-csv-data",
      "how-to-make-a-comparison-chart-in-excel",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-visualize-employee-performance-data",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "visualize employee performance data",
    titleTag: "How to Visualize Employee Performance Data | Distill",
    metaDescription: "Turn employee performance data from a CSV into clear charts using Excel, Google Sheets, or Distill. Free to use, no account required.",
    h1: "How to Visualize Employee Performance Data",
    whatIsLabel: "employee performance chart",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-make-a-bar-chart-from-csv-data",
    ],
  },
  {
    slug: "how-to-make-a-box-plot-from-raw-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "box plot from raw data",
    titleTag: "How to Make a Box Plot from Raw Data | Distill",
    metaDescription: "Learn how to make a box plot from raw data in Excel and Google Sheets. Or upload your CSV to Distill and get one generated automatically. Free to use.",
    h1: "How to Make a Box Plot from Raw Data",
    whatIsLabel: "box plot",
    relatedSlugs: [
      "how-to-make-a-histogram-from-raw-data",
      "how-to-make-a-scatter-plot-from-csv-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-funnel-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "funnel chart from CSV",
    titleTag: "How to Make a Funnel Chart from CSV | Distill",
    metaDescription: "Learn how to make a funnel chart from a CSV in Excel and Google Sheets. Or upload your CSV to Distill and get one generated instantly. Free to use.",
    h1: "How to Make a Funnel Chart from CSV Data",
    whatIsLabel: "funnel chart",
    relatedSlugs: [
      "how-to-visualize-marketing-funnel-data",
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-make-a-waterfall-chart-in-excel",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "waterfall chart in Excel",
    titleTag: "How to Make a Waterfall Chart in Excel | Distill",
    metaDescription: "Learn how to make a waterfall chart in Excel and Google Sheets to show running totals and variances. Or upload your CSV to Distill and get one instantly.",
    h1: "How to Make a Waterfall Chart in Excel",
    whatIsLabel: "waterfall chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv-data",
      "how-to-make-a-stacked-bar-chart",
      "how-to-turn-a-csv-into-a-chart-instantly",
    ],
  },
  {
    slug: "how-to-visualize-customer-data-from-a-spreadsheet",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "visualize customer data from a spreadsheet",
    titleTag: "How to Visualize Customer Data from a Spreadsheet | Distill",
    metaDescription: "Turn customer data from a spreadsheet into clear charts in Excel or Google Sheets. Or upload your CSV to Distill and get instant visuals. Free to use.",
    h1: "How to Visualize Customer Data from a Spreadsheet",
    whatIsLabel: "customer data visualization",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-a-spreadsheet",
      "how-to-create-a-kpi-dashboard-from-csv",
      "how-to-make-a-bar-chart-from-csv-data",
    ],
  },
];

export default topics;
