export const topics = [
  // Cluster 1: Chart Types
  {
    slug: "how-to-make-a-bar-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a bar chart from CSV",
    titleTag: "How to Make a Bar Chart from CSV | Distill",
    metaDescription: "Learn how to make a bar chart from a CSV file in Excel, Google Sheets, or Distill. Auto-generate charts instantly by uploading your CSV.",
    h1: "How to Make a Bar Chart from a CSV File",
    whatIsLabel: "bar chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-from-csv",
      "how-to-make-a-pie-chart-from-csv",
      "how-to-visualize-time-series-data",
    ],
  },
  {
    slug: "how-to-make-a-line-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a line chart from CSV",
    titleTag: "How to Make a Line Chart from CSV | Distill",
    metaDescription: "Make a line chart from a CSV file in Excel, Google Sheets, or Distill. Upload your CSV and get charts instantly — no account required.",
    h1: "How to Make a Line Chart from a CSV File",
    whatIsLabel: "line chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv",
      "how-to-visualize-time-series-data",
      "how-to-create-an-area-chart-from-csv",
    ],
  },
  {
    slug: "how-to-make-a-pie-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a pie chart from CSV",
    titleTag: "How to Make a Pie Chart from CSV | Distill",
    metaDescription: "Turn CSV data into a pie chart in Excel, Google Sheets, or Distill. Upload your file and auto-generate charts in seconds for free.",
    h1: "How to Make a Pie Chart from a CSV File",
    whatIsLabel: "pie chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv",
      "how-to-make-a-donut-chart",
      "how-to-make-a-scatter-plot-from-csv",
    ],
  },
  {
    slug: "how-to-make-a-scatter-plot-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a scatter plot from CSV",
    titleTag: "How to Make a Scatter Plot from CSV | Distill",
    metaDescription: "Create a scatter plot from CSV data in Excel, Google Sheets, or Distill. Upload your CSV and visualize correlations instantly.",
    h1: "How to Make a Scatter Plot from a CSV File",
    whatIsLabel: "scatter plot",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv",
      "how-to-make-a-histogram-from-data",
      "how-to-compare-two-datasets-in-a-chart",
    ],
  },
  {
    slug: "how-to-make-a-histogram-from-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a histogram from data",
    titleTag: "How to Make a Histogram from Data | Distill",
    metaDescription: "Build a histogram from raw data in Excel, Google Sheets, or Distill. Upload a CSV and auto-generate distribution charts instantly.",
    h1: "How to Make a Histogram from Raw Data",
    whatIsLabel: "histogram",
    relatedSlugs: [
      "how-to-make-a-scatter-plot-from-csv",
      "how-to-make-a-box-plot-from-raw-data",
      "how-to-make-a-bar-chart-from-csv",
    ],
  },
  {
    slug: "how-to-make-a-donut-chart",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a donut chart",
    titleTag: "How to Make a Donut Chart | Distill",
    metaDescription: "Create a donut chart in Excel, Google Sheets, or Distill from a CSV file. Visualize part-to-whole data with a cleaner look than a pie chart.",
    h1: "How to Make a Donut Chart",
    whatIsLabel: "donut chart",
    relatedSlugs: [
      "how-to-make-a-pie-chart-from-csv",
      "how-to-make-a-bar-chart-from-csv",
      "how-to-make-a-treemap-chart",
    ],
  },
  {
    slug: "how-to-create-an-area-chart-from-csv",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to create an area chart from CSV",
    titleTag: "How to Create an Area Chart from CSV | Distill",
    metaDescription: "Turn CSV data into an area chart in Excel, Google Sheets, or Distill. Upload your file and visualize trends over time in seconds.",
    h1: "How to Create an Area Chart from a CSV File",
    whatIsLabel: "area chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-from-csv",
      "how-to-visualize-time-series-data",
      "how-to-make-a-bar-chart-from-csv",
    ],
  },
  {
    slug: "how-to-make-a-box-plot-from-raw-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a box plot from raw data",
    titleTag: "How to Make a Box Plot from Raw Data | Distill",
    metaDescription: "Create a box plot from raw data in Excel, Google Sheets, or Distill. Visualize distributions, medians, and outliers from a CSV upload.",
    h1: "How to Make a Box Plot from Raw Data",
    whatIsLabel: "box plot",
    relatedSlugs: [
      "how-to-make-a-histogram-from-data",
      "how-to-make-a-scatter-plot-from-csv",
      "how-to-visualize-time-series-data",
    ],
  },
  {
    slug: "how-to-make-a-treemap-chart",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to make a treemap chart",
    titleTag: "How to Make a Treemap Chart | Distill",
    metaDescription: "Build a treemap chart in Excel, Google Sheets, or Distill from a CSV. Visualize hierarchical and proportional data with nested rectangles.",
    h1: "How to Make a Treemap Chart",
    whatIsLabel: "treemap chart",
    relatedSlugs: [
      "how-to-make-a-donut-chart",
      "how-to-make-a-bar-chart-from-csv",
      "how-to-create-a-heatmap-from-data",
    ],
  },
  // Cluster 2: Business Use Cases
  {
    slug: "how-to-build-a-sales-dashboard-from-csv",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "how to build a sales dashboard from CSV",
    titleTag: "How to Build a Sales Dashboard from CSV | Distill",
    metaDescription: "Build a sales dashboard from a CSV file using Excel, Google Sheets, or Distill. Upload and auto-generate charts to track revenue and pipeline.",
    h1: "How to Build a Sales Dashboard from a CSV File",
    whatIsLabel: "sales dashboard",
    relatedSlugs: [
      "how-to-visualize-revenue-trends",
      "how-to-make-a-funnel-chart-from-csv",
      "how-to-make-a-bar-chart-from-csv",
    ],
  },
  {
    slug: "how-to-visualize-revenue-trends",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "how to visualize revenue trends",
    titleTag: "How to Visualize Revenue Trends | Distill",
    metaDescription: "Visualize revenue trends from a CSV in Excel, Google Sheets, or Distill. Get line charts and AI-written summaries from your data instantly.",
    h1: "How to Visualize Revenue Trends from Your Data",
    whatIsLabel: "revenue trend chart",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-csv",
      "how-to-make-a-line-chart-from-csv",
      "how-to-visualize-time-series-data",
    ],
  },
  {
    slug: "how-to-make-a-funnel-chart-from-csv",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "how to make a funnel chart from CSV",
    titleTag: "How to Make a Funnel Chart from CSV | Distill",
    metaDescription: "Create a funnel chart from a CSV in Excel, Google Sheets, or Distill. Visualize conversion stages and drop-off rates instantly.",
    h1: "How to Make a Funnel Chart from a CSV File",
    whatIsLabel: "funnel chart",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-csv",
      "how-to-visualize-customer-data-from-a-spreadsheet",
      "how-to-make-a-bar-chart-from-csv",
    ],
  },
  {
    slug: "how-to-visualize-employee-performance-data",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "how to visualize employee performance data",
    titleTag: "How to Visualize Employee Performance Data | Distill",
    metaDescription: "Visualize employee performance data from a CSV using Excel, Google Sheets, or Distill. Auto-generate charts and summaries from your HR spreadsheet.",
    h1: "How to Visualize Employee Performance Data",
    whatIsLabel: "employee performance chart",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-csv",
      "how-to-make-a-bar-chart-from-csv",
      "how-to-visualize-survey-results",
    ],
  },
  {
    slug: "how-to-visualize-customer-data-from-a-spreadsheet",
    cluster: 2,
    clusterName: "Business Use Cases",
    primaryKeyword: "how to visualize customer data from a spreadsheet",
    titleTag: "How to Visualize Customer Data from a Spreadsheet | Distill",
    metaDescription: "Turn customer spreadsheet data into charts using Excel, Google Sheets, or Distill. Upload a CSV and get instant visualizations with no setup.",
    h1: "How to Visualize Customer Data from a Spreadsheet",
    whatIsLabel: "customer data chart",
    relatedSlugs: [
      "how-to-build-a-sales-dashboard-from-csv",
      "how-to-make-a-funnel-chart-from-csv",
      "how-to-visualize-survey-results",
    ],
  },
  // Cluster 3: CSV to Charts
  {
    slug: "how-to-convert-csv-to-chart-online",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "how to convert CSV to chart online",
    titleTag: "How to Convert CSV to Chart Online | Distill",
    metaDescription: "Convert a CSV to a chart online for free with Distill. Upload your file and get auto-generated visualizations in seconds, no account required.",
    h1: "How to Convert a CSV to a Chart Online",
    whatIsLabel: "CSV chart converter",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv",
      "how-to-share-a-data-dashboard",
      "how-to-make-a-line-chart-from-csv",
    ],
  },
  {
    slug: "how-to-share-a-data-dashboard",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "how to share a data dashboard",
    titleTag: "How to Share a Data Dashboard | Distill",
    metaDescription: "Share a data dashboard from CSV in Distill, Google Sheets, or Excel. Create a shareable link to your charts in seconds, no coding required.",
    h1: "How to Share a Data Dashboard",
    whatIsLabel: "shareable data dashboard",
    relatedSlugs: [
      "how-to-convert-csv-to-chart-online",
      "how-to-build-a-sales-dashboard-from-csv",
      "how-to-make-a-bar-chart-from-csv",
    ],
  },
  {
    slug: "how-to-visualize-survey-results",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "how to visualize survey results",
    titleTag: "How to Visualize Survey Results | Distill",
    metaDescription: "Visualize survey results from a CSV in Excel, Google Sheets, or Distill. Upload your data and get charts and summaries automatically.",
    h1: "How to Visualize Survey Results from a CSV",
    whatIsLabel: "survey results chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv",
      "how-to-make-a-pie-chart-from-csv",
      "how-to-convert-csv-to-chart-online",
    ],
  },
  {
    slug: "how-to-create-a-heatmap-from-data",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "how to create a heatmap from data",
    titleTag: "How to Create a Heatmap from Data | Distill",
    metaDescription: "Create a heatmap from CSV data in Excel, Google Sheets, or Distill. Upload your file and visualize density and patterns across two dimensions.",
    h1: "How to Create a Heatmap from Data",
    whatIsLabel: "heatmap",
    relatedSlugs: [
      "how-to-make-a-treemap-chart",
      "how-to-make-a-scatter-plot-from-csv",
      "how-to-convert-csv-to-chart-online",
    ],
  },
  {
    slug: "how-to-compare-two-datasets-in-a-chart",
    cluster: 3,
    clusterName: "CSV to Charts",
    primaryKeyword: "how to compare two datasets in a chart",
    titleTag: "How to Compare Two Datasets in a Chart | Distill",
    metaDescription: "Compare two datasets in a chart using Excel, Google Sheets, or Distill. Upload a CSV and auto-generate side-by-side visualizations instantly.",
    h1: "How to Compare Two Datasets in a Chart",
    whatIsLabel: "comparison chart",
    relatedSlugs: [
      "how-to-make-a-bar-chart-from-csv",
      "how-to-make-a-scatter-plot-from-csv",
      "how-to-convert-csv-to-chart-online",
    ],
  },
  // New article
  {
    slug: "how-to-visualize-time-series-data",
    cluster: 1,
    clusterName: "Chart Types",
    primaryKeyword: "how to visualize time series data",
    titleTag: "How to Visualize Time Series Data | Distill",
    metaDescription: "Visualize time series data from a CSV in Excel, Google Sheets, or Distill. Upload your file and get line charts and trend summaries instantly.",
    h1: "How to Visualize Time Series Data",
    whatIsLabel: "time series chart",
    relatedSlugs: [
      "how-to-make-a-line-chart-from-csv",
      "how-to-create-an-area-chart-from-csv",
      "how-to-visualize-revenue-trends",
    ],
  },
];

export default topics;
